version: "3.8"

services:
  postgresdb:
    image: postgres
    container_name: postgresdb
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=persondb
      - POSTGRES_PASSWORD=personpassword
    ports:
      - "5432:5432"
  app:
    depends_on:
      - postgresdb
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresdb:5432/persondb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=personpassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update